#%RAML 0.8
title: Brexit System Layer
version: 1.0.development
baseUri: http://mule360.io/api/brexit/system/
/areas:
  displayName: Areas
  get:
    description: Get a list of all the areas
    responses:
      200:
        body:
          application/json:
            example: |
              [
                 {
                    "_id": {
                      "time": 1471828347000,
                      "machine": -1950106814,
                      "timeSecond": 1471828347,
                      "inc": 67449346,
                      "new": false
                    },
                    "_class": "io.dd.brexit.model.Area",
                    "areaSize": 21574981.58999999,
                    "areaTypeCode": "LBO",
                    "areaTypeName": "London borough",
                    "country": "England",
                    "electorate": 167820,
                    "femalePopulation": 141787,
                    "gss": "E09000030",
                    "identity": "117",
                    "latitudeMaximum": "51.544632740648865",
                    "latitudeMiddle": "51.515687169175585",
                    "latitudeMinimum": "51.484448635185025",
                    "leaveVotes": 35224,
                    "links": [],
                    "longitudeMaximum": "0.009886230454418358",
                    "longitudeMiddle": "-0.03463999651847128",
                    "longitudeMinimum": "-0.08016930267471568",
                    "malePopulation": 153449,
                    "mapItId": "2506",
                    "name": "Tower Hamlets Borough Council",
                    "ons": "00BG",
                    "regionCode": "E12000007",
                    "regionName": "London",
                    "registered": 108421,
                    "remainVotes": 73011,
                    "totalPopulation": 295236,
                    "unitId": "11185",
                    "validVotes": 108235
                  }
              ]
  /{identity}:
    displayName: Area
    get:
      description: A single Area
      responses:
        200:
          body:
            application/json:
              example: |
                 {
                    "_id": {
                      "time": 1471828347000,
                      "machine": -1950106814,
                      "timeSecond": 1471828347,
                      "inc": 67449346,
                      "new": false
                    },
                    "_class": "io.dd.brexit.model.Area",
                    "areaSize": 21574981.58999999,
                    "areaTypeCode": "LBO",
                    "areaTypeName": "London borough",
                    "country": "England",
                    "electorate": 167820,
                    "femalePopulation": 141787,
                    "gss": "E09000030",
                    "identity": "117",
                    "latitudeMaximum": "51.544632740648865",
                    "latitudeMiddle": "51.515687169175585",
                    "latitudeMinimum": "51.484448635185025",
                    "leaveVotes": 35224,
                    "links": [],
                    "longitudeMaximum": "0.009886230454418358",
                    "longitudeMiddle": "-0.03463999651847128",
                    "longitudeMinimum": "-0.08016930267471568",
                    "malePopulation": 153449,
                    "mapItId": "2506",
                    "name": "Tower Hamlets Borough Council",
                    "ons": "00BG",
                    "regionCode": "E12000007",
                    "regionName": "London",
                    "registered": 108421,
                    "remainVotes": 73011,
                    "totalPopulation": 295236,
                    "unitId": "11185",
                    "validVotes": 108235
                  }